{% set name = "mariadb" %}
{% set version = "1.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mariadb-{{ version }}.tar.gz
  sha256: 50b02ff2c78b1b4f4628a054e3c8c7dd92972137727a5cc309a64c9ed20c878c

build:
  number: 1
  rpaths:
    - lib/mariadb

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - zlib  # [win]
  host:
    - python
    - wheel
    - setuptools
    - packaging
    - pip
    - mariadb-connector-c
  run:
    - python
    - packaging
    - mariadb-connector-c
    - zlib  # [win]

test:
  imports:
    - mariadb
    - mariadb.constants
  commands:
    - pip check
  requires:
    - pip
    - setuptools

about:
  home: https://www.github.com/mariadb-corporation/mariadb-connector-python
  summary: Python MariaDB extension
  description: |
    MariaDB Connector/Python enables python programs to access MariaDB and MySQL databases, using an API which is compliant with the Python DB API 2.0 (PEP-249). It is written in C and uses MariaDB Connector/C client library for client server communication.
  license: LGPL-2.1-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - avgra3
