{% set name = "mariadb" %}
{% set version = "1.1.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mariadb-{{ version }}.tar.gz
  sha256: a332893e3ef7ceb7970ab4bd7c844bcb4bd68a051ca51313566f9808d7411f2d

build:
  number: 1
  rpaths:
    - lib/mariadb

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - python >=3.8
    - wheel
    - setuptools
    - packaging
    - pip
    - mariadb-connector-c
  run:
    - python >=3.8
    - packaging
    - mariadb-connector-c

test:
  imports:
    - mariadb
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.github.com/mariadb-corporation/mariadb-connector-python
  summary: Python MariaDB extension
  license: LGPL-2.1-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - avgra3
